CREATE DATABASE FilmesBD_Torloni;
GO

USE FilmesBD_Torloni;
GO

CREATE TABLE Genero(
	IdGenero VARCHAR(40) PRIMARY KEY,
	Nome VARCHAR(100) NOT NULL
);
GO

CREATE TABLE Filme(
	IdFilme VARCHAR(40) PRIMARY KEY,
	Imagem VARCHAR(100),
	Titulo VARCHAR(100) NOT NULL,
	IdGenero VARCHAR(40) FOREIGN KEY REFERENCES Genero(IdGenero)
);
GO

CREATE TABLE Usuario(
	IdUsuario VARCHAR(40) PRIMARY KEY,
	Nome VARCHAR(100) NOT NULL,
	Email VARCHAR(256) UNIQUE NOT NULL,
	Senha VARCHAR(60) NOT NULL
);